### PR TITLE
Feature/interactables

### PR DESCRIPTION
**Pull request by WillTarte**
#13 
Implements:
- Explosive barrels (prefab you can drag and drop into the scene)
- Chests (can hold different items, prefab you can drag and drop)
- Breakable Bridges (you have to use the tile palette to draw the tiles)
- Spikes (same thing: draw spikes using the tile palette)

@tedgag I added 2 tiles to the Level tile palette you were using. The  metal spike is the spikes I implemented, and the duplicate wooden bridge tile is actually the breakable bridge tile

I also had to modify Level1 to add the bridges and spikes and removed some things (like existing weapons and enemies)

### CODE REVIEW

**Review by tedgag — CHANGES_REQUESTED** [review]
Looks nice! The interactable works mostly as expected, although I have some things that i think we should changes and also I found some bugs while playing around with them:

1. It would be nice to add the explosion effects that Claudia created for the emus to the explosive barrels.
2. I noticed this weird animation bug with the new bridge sprites, it doesn't happen with the old bridge sprites

image

3. I'm confused about this bridge grid, do we really need to have the 3 bridge tilemaps?

image

4. When I have full ammo on my guns I am unable to open chests. If I have full health and am missing ammo I can open them however.

5. I don't think ammo pickups work the way we want to, it should probably replenish a percentage of your total ammo capacity instead of a set number of ammo, since for example the assault rifle will use more ammo than the shotgun. Also, I noticed that if I am missing 1 bullet and the ammo box gives me 2, it will only gives me one and the ammo box will stay on the ground. We should probably make it that we collect the full ammo box and the excess ammo that we would collect is discarded (I think it already works this way for health pickups). It would work the same way in the percentage system, i.e. if I am missing 5% of my total ammo count and the box gives me 10% back, then I will get 5% and the rest will be discarded.

6. When in range of both the chest and another interactable (like the grenade) and I press 'e', the chest will open, but then if I press 'e' again I can't pickup the grenade. I have to move out of the interaction range of the grenade and back in to be able to pick it up.

**Review by ClaudiaLapalme — CHANGES_REQUESTED** [review]
1. I've noticed that the emus are back to being one-shot killed. Would it be possible to go back to varied HP levels?
2. I've noticed a bug where the grenades tie to the main character and follows him until it explodes (and damages the player). This happened to me all three times that i tried to throw the grenade
3. If I go underground, I get soft locked into the underground since the ladder is not wide enough for me to pass through
4. The melee emu does not do damage anymore
5. The enemy physics layer is no longer being ignored
6. Heavy refactoring within a feature PR (moving files) makes it hard for me to review the code because I don't know what's new and what's old



Stuck underground:
image

**Comment by WillTarte** [comment]
> Looks nice! The interactable works mostly as expected, although I have some things that i think we should changes and also I found some bugs while playing around with them:
> 
> 1. It would be nice to add the explosion effects that Claudia created for the emus to the explosive barrels.
> 2. I noticed this weird animation bug with the new bridge sprites, it doesn't happen with the old bridge sprites
> 
> image
> 
> 1. I'm confused about this bridge grid, do we really need to have the 3 bridge tilemaps?
> 
> image
> 
> 1. When I have full ammo on my guns I am unable to open chests. If I have full health and am missing ammo I can open them however.
> 2. I don't think ammo pickups work the way we want to, it should probably replenish a percentage of your total ammo capacity instead of a set number of ammo, since for example the assault rifle will use more ammo than the shotgun. Also, I noticed that if I am missing 1 bullet and the ammo box gives me 2, it will only gives me one and the ammo box will stay on the ground. We should probably make it that we collect the full ammo box and the excess ammo that we would collect is discarded (I think it already works this way for health pickups). It would work the same way in the percentage system, i.e. if I am missing 5% of my total ammo count and the box gives me 10% back, then I will get 5% and the rest will be discarded.
> 3. When in range of both the chest and another interactable (like the grenade) and I press 'e', the chest will open, but then if I press 'e' again I can't pickup the grenade. I have to move out of the interaction range of the grenade and back in to be able to pick it up.

1. Done for grenades and barrels
2. Fixed
3. It's more efficient that way, but not necessary (and partly due to Unity's TileMap API being bad)
4. Probably fixed by 5
5. Fixed
6. Fixed

**Comment by WillTarte** [comment]
> 1. I've noticed that the emus are back to being one-shot killed. Would it be possible to go back to varied HP levels?
> 2. I've noticed a bug where the grenades tie to the main character and follows him until it explodes (and damages the player). This happened to me all three times that i tried to throw the grenade
> 3. If I go underground, I get soft locked into the underground since the ladder is not wide enough for me to pass through
> 4. The melee emu does not do damage anymore
> 5. The enemy physics layer is no longer being ignored
> 6. Heavy refactoring within a feature PR (moving files) makes it hard for me to review the code because I don't know what's new and what's old
> 
> Stuck underground:
> image

1. I tested this by setting the EMU hp higher, and it works as intended. Either we need to increase the emu HP or decrease the weapon damage
2. I'm aware of a bug like this, but it happens inconsistently. I'll create a bug ticket for it.
3. This is not related to this PR. Maybe we should create a ticket for this
4. No issues with this on my end
5. On my end it works properly (player ignores enemy layer)

**Review by tedgag — APPROVED** [review]
Nice! All my comments were fixed and I didn't find anything else related to this PR

**Review by ClaudiaLapalme — APPROVED** [review]

**Comment by WillTarte** [comment]
I've seen the bug mentioned by claudia (grenade not being thrown properly) but it's extremely inconsistent and I've been unable to reproduce it in a while

**Pull request merged**
