### PR TITLE
Enhancement/player anim

### PR DESCRIPTION
**Pull request by Wmbat**
All player animation is done

### CODE REVIEW

**Review by ClaudiaLapalme — CHANGES_REQUESTED** [review]
1. I am not seeing the knife attack animation when I press K and I'm not sure if it's because the animation isn't animating or the knife isn't attacking
2. The bullets aren't aligned with the gun

This is awesome, great job!

**Comment by Aleoris** [comment]
Same comments as Claudia...
1. It seems that we only miss the animation because I was able to kill emus using the knife
2. Only the assault rifle isn't aligned properly

**Review by ClaudiaLapalme — APPROVED** [review]
hot

**Review by Aleoris — APPROVED** [review]
Nice job 💯 
Can you create a bug to align the bullets and the weapons please

**Comment by ClaudiaLapalme** [comment]
1. I would put the main menu song in the levels as well 
2. The footsteps sound like gun shots. I think that a different sound (and a lot quieter) would be a lot better

great job on the rest!!!!

**Pull request merged**
