### PR TITLE
Player going down through platforms

### PR DESCRIPTION
**Pull request by Wmbat**
Implements issue #42

The player can now go through platforms when pressing down whilst standing on a platform

### CODE REVIEW

**Comment by ClaudiaLapalme** [comment]
There is a bug where sometimes if I climb a ladder, the character senses the air as being solid ground and can walk on air or gets stuck falling

Ex: 
image

Also, I can't seem to go through the platforms that bring me underground. I just see a falling animation

Ex: 
image

**Review by ClaudiaLapalme — CHANGES_REQUESTED** [review]
See comment above

**Comment by Wmbat** [comment]
Hum, that is because the edge of the edge collider are fucked, if you actually look at the boundaries set by the edge collider stuff. it goes a lot back and that's why the character does stuff like this. I didn't setup the edge collider stuff and i'm not quite sure how to effectively change it

**Comment by ClaudiaLapalme** [comment]
@tedgag were you the one who did the edge colliders?

**Comment by tedgag** [comment]
> @tedgag were you the one who did the edge colliders?

As far as I know the colliders are applied automatically to the sprite when I add them to the scene. I think you can change the physic collider for each sprite at will tho, as you can see in this screen shot. Basically you can navigate to the tiles in the tilemaps/images folder, click a sprite and click on sprite editor on the right. When the sprite editor window opens, you can select custom physics shape on the top left and click "generate" to be able to create a custom outline. Another solution is also simply setting the collider type to "grid" when selecting he sprite, it will take the space of a grid cell.

image

**Review by ClaudiaLapalme — APPROVED** [review]

**Pull request merged**
