### PR TITLE
Level 2 tilemap

### PR DESCRIPTION
**Pull request by tedgag**
Tile map for level 2. I also added interactable such as platform, ladders and spikes. To test, simply play the level 2 and see if you can get to the end of the level. You might get stuck in some places since going down platforms is not implemented yet.
*Note: I also increased the jump strength of the player because it was too low. I also made the collider on the player more thin so they can go down 1 block wide holes.

### CODE REVIEW

**Review by ClaudiaLapalme — CHANGES_REQUESTED** [review]
* Going up ladders from the underground is still a bit tricky. Personally, I think that we should make ladders 2 units wide for user-friendliness purpose

* The walls are slippery. I think that some of the assets have friction on them

**Comment by Aleoris** [comment]
1. When I try to jump over a block and hit it by mistake, I stay stuck to it until I release A or D (Probably related to 4)
2. I tried to go in the building on the left of spawn, but I stay stuck in the stairs and have to restart the game
(same for all the stairs in buildings, spamming space unstuck some times)
3. The spikes in the cave should kill the player, not deal 1 dmg ( i guess it will be implemented after)
4. I can jump using walls (issue in player or tiles?)
walljump_bug
5. Love the broken building design. However not sure how the player is supposed to continue from there. I had to use wall jump to continue
6. After the bridge, there is a cave full of spikes with (i think) a reward at the end. I don't know if I'm just bad, but standing on the safe tiles deals damage anyway. Maybe not put the tiles at the same level as the spikes.
image
7. If you jump from very high, you end up being stuck in the floor. (used wall jump for that tho)
image
8. How do you go in the last build? Are we supposed to go in the last building?

**Comment by tedgag** [comment]
@Aleoris 
1. This is the same bug that @ClaudiaLapalme was talking about and is most likely related to the movement system. I created a new bug issue for: https://github.com/WillTarte/EMU/issues/58 
2. This is due to the fact that we can't go down platforms for now, I think it should be fixed when https://github.com/WillTarte/EMU/pull/55 is merged
3. I agree that they should do more than 1 dmg, probably not instant kill the player tho. We can talk about it during the enext meeting.
4. Same thing as 1
5. I added some to make this easier to navigate. You can go either bellow using the ladder on the bottom right or above by climbing over the tipped off building
image
6. Just get gud lol (jk). You're right, having the block the same height as the spikes cause the player to take dmg, so I made the pillars higher.
7. This bug is probably due to Unity's physic engine and not on our end, I created an issue in case we have time to fix this: . In the meantime, there are no high enough jumps for this to happen during regular gameplay, you have to glitch out to reproduce this.

**Comment by ClaudiaLapalme** [comment]
in regards to #7, this problem has been persistent since the beginning and not in the scope of this PR

I think that the player is able to climb the walls a little too much, but that should be fixed in the issue, not in this PR

**Comment by ClaudiaLapalme** [comment]
I am unable to recreate @Aleoris's wall climbing / flying

**Comment by ClaudiaLapalme** [comment]
I'm stuck here

image

**Review by ClaudiaLapalme — APPROVED** [review]
Approved based off of our discussions

**Review by Aleoris — APPROVED** [review]

**Pull request merged**
