### PR TITLE
Boss 2 fight mechanism

### PR DESCRIPTION
**Pull request by ClaudiaLapalme**
* Teleports to player to squash him
* Shoots at the player when they are both on the ground

### CODE REVIEW

**Comment by WillTarte** [comment]
1. There's a weird bug that doesn't happen on master, where directions causes some weird camera jitter.
2. To make the fight a bit more interactive, I think the boss should shoot the bullets towards the location of the player (not just in the facing direction) so it makes it more about dodging the bullets.
3. I think making the boss' bullets slightly bigger would also be better.

**Comment by Aleoris** [comment]
I fixed the camera bug. Ill let claudia address the two others comments since she did the weapon of the boss

**Comment by tedgag** [comment]
I agree that the boss's bullets should be bigger. The boss has way too much HP, it should probably be scaled down to 40. I don't think he should aim at the player while shooting or else it would be too hard

**Review by tedgag — APPROVED** [review]
I like the new shoot mechanic actually, makes it more faire for the player. The HP will have to be tweaked before we finish the game, but the rest looks good

**Pull request merged**
